name: 🐞 Bug Report
description: Help improve FileSentry by reporting a bug
title: "[Bug] <Short bug summary>"
labels: ["bug"]
assignees:
  - raghul-tech

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Thanks for helping us improve FileSentry!
        Please fill out the details below to report a bug clearly.

  - type: input
    id: environment
    attributes:
      label: 💻 Environment
      description: Tell us about your system and setup
      placeholder: "e.g. Windows 11, Java 17, FileSentry 1.0.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 😕 What went wrong?
      description: Describe the problem or error clearly.
      placeholder: "Example: File change detection doesn't trigger on save."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🧪 Steps to Reproduce
      description: List the steps to see the bug.
      placeholder: |
        Example:
        1. Save a file in Windows using VS Code
        2. Watcher doesn't detect the change
        3. No callback is triggered
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ What should have happened?
      description: Describe what you expected instead.
      placeholder: "I expected the file change callback to be triggered."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📄 Error Message or Logs (optional)
      description: Paste any error message or stack trace if you have it.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshot (optional)
      description: Add a screenshot if it helps explain the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Before submitting...
      options:
        - label: I checked for [existing issues](https://github.com/raghul-tech/FileSentry/issues)
          required: true
        - label: I’m using the **latest version** of FileSentry
          required: true
        - label: I provided all required information
          required: true
